# Generated by Django 4.0.4 on 2022-06-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_direccion_usuario_suscrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_carrito',
            name='id_producto',
            field=models.IntegerField(null=True),
        ),
    ]
