# Generated by Django 4.0.4 on 2022-06-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_items_carrito_id_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items_carrito',
            name='id_producto',
        ),
    ]
