# Generated by Django 4.0.4 on 2022-06-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_historialcompras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
